In [1]:
# Import all dependencies
import requests
import json
import pandas as pd
import wikipedia as wp
import pyowm
from config import api_key

In [2]:
# Load city_df3 CSV file into dataFrame
df = pd.read_csv('california_cities.csv')
df.head(10)

,Unnamed: 0,city,type,county,state,lat,lng
0,2,Adelanto,City,San Bernardino,california,34.582770,-117.409215
1,3,Agoura Hills,City,Los Angeles,california,34.153340,-118.761676
2,4,Alameda,City,Alameda,california,37.765206,-122.241636
3,5,Albany,City,Alameda,california,37.886870,-122.297748
4,6,Alhambra,City,Los Angeles,california,34.095287,-118.127015
5,7,Aliso Viejo,City,Orange,california,33.568461,-117.726298
6,8,Alturas,City,Modoc,california,41.487115,-120.542455
7,9,Amador City,City,Amador,california,38.419355,-120.824103
8,10,American Canyon,City,Napa,california,38.174918,-122.260804
9,11,Anaheim,City,Orange,california,33.836593,-117.914301

In [3]:
# City, Latitude, and Longitude
city_df = df.drop(['Unnamed: 0'], axis=1)
city_df.head()

           city  type          county       state        lat         lng
0      Adelanto  City  San Bernardino  california  34.582770 -117.409215
1  Agoura Hills  City     Los Angeles  california  34.153340 -118.761676
2       Alameda  City         Alameda  california  37.765206 -122.241636
3        Albany  City         Alameda  california  37.886870 -122.297748
4      Alhambra  City     Los Angeles  california  34.095287 -118.127015

In [4]:
# import the module OWM
owm = pyowm.OWM(api_key)

In [3]:
# Assign the coordinates to uvi
uvi = owm.uvindex_around_coords(40.712784, -74.005941)

NameError: name 'owm' is not defined

In [6]:
# A forecast UV Index for New York City
uv_list = owm.uvindex_forecast_around_coords(40.71, -74.00)
uv_list[0]

In [7]:
# the value of the UV Index for the assigned city fro, UVI
uvi.get_value()

1.3

In [10]:
# Loop through the dataframe and push the UV Index for each city to uv_index
uv_index = []
for i, r in city_df.iterrows():
    uvi = owm.uvindex_around_coords(r.loc['lat'], r.loc['lng'])
    uv_index.append(uvi.get_value())

In [12]:
# Test
for i,r in city_df.iterrows():
    print(r.loc['lat'], r.loc['lng'])

34.582769899999995 -117.40921499999999
34.1533395 -118.7616764
37.7652065 -122.2416355
37.88687 -122.29774750000001
34.095287 -118.1270146
33.5684605 -117.7262981
41.4871146 -120.54245549999999
38.41935529999999 -120.82410300000001
38.174917799999996 -122.2608044
33.8365932 -117.91430120000001
40.448208 -122.2977815
38.06778320000001 -120.53852990000001
38.0049214 -121.80578899999999
34.5008311 -117.18587590000001
34.139729200000005 -118.0353449
40.866516600000004 -124.0828396
35.118586799999996 -120.59072520000001
33.8658484 -118.08312120000001
35.201798600000004 -118.833105
35.4894169 -120.67072549999999
37.46132720000001 -122.19774299999999
37.3477174 -120.60908400000001
38.8965654 -121.07689009999999
33.3428193 -118.32822790000002
36.0041223 -120.12902720000001
34.1336186 -117.90756270000001
35.3732921 -119.0187125
34.0852868 -117.96089779999998
33.9255713 -116.87641029999999
34.89579570000001 -117.01728259999999
33.929460600000006 -116.977248
33.9775142 -118.1870156
33.965291799999996 -118.1514588
33.881681799999996 -118.1170117
37.5202145 -122.27580079999998
37.872704399999996 -122.46441709999999
38.049365 -122.1585777
37.87159260000001 -122.272747
34.073620399999996 -118.40035630000001
34.243896299999996 -116.9114215
39.4123876 -121.71275130000001
37.3614238 -118.3996636
40.882907200000005 -123.9839488
33.6177725 -114.5882607
34.1469511 -117.97089820000001
32.9786566 -115.530267
33.916475 -117.9002918
37.931868 -121.6957863
37.6807661 -122.3999715
34.613597 -120.19265049999998
33.8674044 -117.99813870000001
34.18083920000001 -118.30896609999998
37.5778696 -122.34808999999998
34.1367208 -118.66148090000002
32.6789476 -115.4988834
35.125801 -117.98590379999999
34.0039039 -117.06197549999999
33.1255957 -115.51415379999999
38.5787965 -122.5797054
34.216393700000005 -119.0376023
37.2871651 -121.9499568
33.685021500000005 -117.27309309999998
36.9752283 -121.95329299999999
33.158093300000004 -117.3505939
36.5552386 -121.92328789999999
34.39888380000001 -119.5184564
33.8316745 -118.28169299999999
33.780538799999995 -116.46680359999999
37.5949316 -120.9577098
33.858348299999996 -118.0647871
39.728494399999995 -121.8374777
34.0122346 -117.68894399999999
33.989818799999995 -117.7325848
37.1229997 -120.2601754
32.6400541 -117.0841955
38.7071247 -121.2810611
34.0966764 -117.71977849999999
37.9410341 -121.9357925
38.9582307 -122.62637279999998
38.8054624 -123.01722269999999
36.8252277 -119.70291940000001
33.6803003 -116.17389399999999
36.139678 -120.3601496
39.100729799999996 -120.95327590000001
37.6768779 -122.459695
34.0739016 -117.3136547
39.2143343 -122.0094175
34.0005691 -118.1597929
33.8958492 -118.2200712
37.9779776 -122.0310733
36.098007 -119.56040149999998
39.927657200000006 -122.17915559999999
33.8752935 -117.56643840000001
32.6858853 -117.18308909999999
37.92548060000001 -122.5274755
33.6412156 -117.91882209999999
38.3293416 -122.70966659999999
34.0900091 -117.89033970000001
41.7557501 -124.2025913
33.9605701 -118.1853486
34.021122399999996 -118.3964665
37.322997799999996 -122.03218229999999
33.816936600000005 -118.0368507
37.687924100000004 -122.47020790000002
33.4672256 -117.6981014
37.8215929 -121.9999606
38.5449065 -121.74051670000001
32.9594891 -117.2653146
36.5932934 -121.83495149999999
35.7688425 -119.24705359999999
33.961124 -116.5016784
34.028622600000006 -117.81033670000001
36.5432837 -119.3870656
38.4454641 -121.82329579999998
41.9673696 -121.91806000000001
36.9860582 -120.62657220000001
33.9401088 -118.13315929999999
34.1394513 -117.97728729999999
37.7021521 -121.9357918
41.208208899999995 -122.27195290000002
37.4688273 -122.1410751
33.952463 -117.5848025
32.7947731 -116.96252690000001
32.792 -115.56305139999999
37.9161326 -122.31076499999999
34.0686206 -118.02756670000001
33.9191799 -118.4164652
38.4087993 -121.37161780000001
37.831315999999994 -122.2852473
33.0369867 -117.2919818
37.797427299999995 -120.9966033
33.1192068 -117.086421
41.4568065 -122.8947551
40.80207120000001 -124.16367290000001
36.2960613 -119.1420517
37.987145399999996 -122.5888686
38.24935809999999 -122.03996629999999
36.2977283 -119.2067767
40.5762406 -124.26394409999999
34.3991639 -118.918154
36.8588376 -120.45600719999999
38.6779591 -121.17605829999998
34.0922335 -117.435048
39.445723 -123.8052935
41.6076387 -122.84030990000002
40.5981867 -124.1572756
37.558546500000006 -122.2710788
33.7090212 -117.95440690000001
36.630505799999995 -119.6784697
37.548269700000006 -121.98857190000001
36.737798100000006 -119.78712469999999
33.8703645 -117.9242123
38.2546373 -121.29994850000001
33.774269200000006 -117.9379952
33.8883487 -118.30896240000001
37.0057816 -121.5682751
34.1425078 -118.255075
34.136118700000004 -117.86533899999999
34.4358294 -119.8276389
36.506629499999995 -121.44438059999999
34.0339031 -117.3136544
39.219060799999994 -121.06106059999999
36.320799799999996 -121.2438138
39.363777299999995 -121.69358329999999
35.1216424 -120.6212821
34.971644 -120.57183629999999
37.2577171 -120.99881540000001
37.4635519 -122.4285862
36.3274502 -119.64568440000001
33.8314045 -118.07284240000001
33.9164032 -118.35257479999999
37.6688205 -122.08079640000001
38.6104658 -122.86916090000001
33.7475203 -116.97196840000001
38.017144099999996 -122.28858079999999
33.8622366 -118.39951940000002
34.4263886 -117.3008784
34.16028319999999 -118.6523096
34.1283442 -117.2086513
37.5741032 -122.37941629999999
36.8524545 -121.40160209999999
32.811161199999994 -115.3802643
37.6027244 -120.8664811
33.6594835 -117.99880259999999
33.981681200000004 -118.22507250000001
36.2027308 -120.10291770000002
32.8475528 -115.56943909999998
32.58394439999999 -117.11308490000002
33.717631 -116.34075490000001
33.7205771 -116.2155619
34.0197335 -117.95867539999999
33.9616801 -118.3531311
38.3526912 -120.93271770000001
33.6845673 -117.82650490000002
34.1069527 -117.93534129999999
38.1618614 -121.6116206
38.348802299999996 -120.7741018
33.9971974 -117.48548020000001
36.72355719999999 -120.05987900000001
36.2127439 -121.1260287
36.5138398 -119.5540175
34.2068182 -118.2000277
33.931859100000004 -117.94613700000001
33.9608461 -117.9506186
32.7678287 -117.02308390000002
33.9172357 -118.01200859999999
33.8463218 -118.0461393
34.0200114 -117.94950829999999
33.663357299999994 -116.31000949999999
34.10084260000001 -117.7678355
37.885758200000005 -122.1180201
33.542718900000004 -117.7853568
33.591643299999994 -117.69866040000001
33.5236744 -117.71494380000001
33.610170200000006 -117.7251162
33.668077200000006 -117.3272615
33.6469437 -117.6861023
39.0429506 -122.91582930000001
33.853626899999995 -118.13395630000001
34.6867846 -118.1541632
37.9340915 -122.53525390000001
37.8227046 -121.27661
33.887237 -118.3525744
32.7425516 -117.0314172
36.3007835 -119.7829107
38.891565 -121.29300790000002
36.2030064 -119.08816000000002
39.2757232 -121.6599701
37.6818745 -121.7680088
37.3868826 -120.72353290000001
38.1341477 -121.27221940000001
34.0483474 -117.2611527
33.792239200000004 -118.3150722
34.6391501 -120.4579409
33.770050399999995 -118.1937395
38.8212889 -121.1930041
33.80320089999999 -118.0718894
37.3852183 -122.1141298
37.379662700000004 -122.13746370000001
34.0522342 -118.24368490000002
37.0582786 -120.84991509999999
37.235807799999996 -121.96237509999999
39.67629360000001 -120.2410385
33.930293 -118.21146029999998
36.961335600000005 -120.0607176
34.025921600000004 -118.7797571
37.648546 -118.97207900000001
33.884736100000005 -118.41090890000001
37.797427299999995 -121.21605259999998
35.058858 -119.40095090000001
36.68440289999999 -121.802173
38.0193657 -122.1341321
39.145725299999995 -121.5913547
33.9866807 -118.185349
35.6780104 -119.22927479999998
36.753561100000006 -120.3815574
33.6971468 -117.185294
37.4529598 -122.1817252
37.3021632 -120.48296770000002
37.906036799999995 -122.5449763
37.5985468 -122.38719420000001
37.4323341 -121.8995741
33.596891299999996 -117.6581562
37.63909719999999 -120.99687820000001
34.14426160000001 -118.0019482
41.7281985 -122.5278007
34.0775104 -117.68977759999999
37.23633299999999 -121.99245800000001
34.0165053 -118.11375349999999
36.600237799999995 -121.8946761
34.0625106 -118.1228476
34.285558 -118.8820414
37.8349263 -122.1296871
33.9424658 -117.2296717
37.130501200000005 -121.65439009999999
35.3659445 -120.8499924
41.30987460000001 -122.3105666
37.3860517 -122.08385109999999
33.553914299999995 -117.21392320000001
38.2975381 -122.28686499999999
32.6781085 -117.0991967
34.8480597 -114.6141315
39.2615606 -121.0160594
37.5296593 -122.0402399
37.31382670000001 -121.02076140000001
33.618882899999996 -117.9298493
33.9311257 -117.54866100000001
33.9022367 -118.08173300000001
38.107419799999995 -122.5697032
37.766594700000006 -120.84715449999999
37.8043637 -122.27111370000002
37.9974219 -121.71245359999999
33.1958696 -117.3794834
34.448049499999996 -119.24288899999999
34.0633443 -117.65088759999999
33.7879139 -117.8531007
36.624394 -119.3137301
37.8771476 -122.17968880000001
39.747380299999996 -122.19637479999999
39.513775200000005 -121.55635900000001
34.1975048 -119.17705159999998
36.6177374 -121.9166215
37.613825299999995 -122.48691940000002
33.7222445 -116.37445559999999
33.8302961 -116.54529209999998
34.5794343 -118.11646129999998
37.441883399999995 -122.14301950000001
33.800571399999995 -118.3900737
39.7596061 -121.62191770000001
33.8894598 -118.15979109999998
36.6116174 -119.52707340000002
34.1477849 -118.1445155
35.6368759 -120.65450220000001
37.471600099999996 -121.12965600000001
33.7825194 -117.22864779999999
38.232417 -122.6366524
33.9830688 -118.09673500000001
37.824371500000005 -122.23163500000001
38.0043667 -122.29885870000001
35.1427533 -120.6412827
38.027976200000005 -121.88468059999998
33.8710729 -117.86275479999999
38.7296252 -120.798546
37.9479786 -122.06079629999999
37.6624312 -121.8746789
38.4818531 -120.84465900000001
38.908798 -123.69307260000001
34.055103 -117.7499909
34.147782899999996 -119.1951074
36.06523 -119.0167679
39.8104567 -120.4691034
37.3841066 -122.23524429999999
32.9628232 -117.0358646
38.5890723 -121.302728
34.10639889999999 -117.5931084
33.739744 -116.41278999999999
33.7444613 -118.3870173
33.640171 -117.602832
40.1784886 -122.23583020000001
40.5865396 -122.3916754
34.055569299999995 -117.1825381
33.8491816 -118.3884078
37.485215200000006 -122.2363548
36.5963395 -119.45040290000001
34.1064001 -117.37032350000001
37.9357576 -122.3477486
35.6224561 -117.6708966
40.4993013 -124.10643689999999
38.15575020000001 -121.6913439
37.7394537 -121.13541409999998
37.7360396 -120.9354895
33.9806005 -117.3754942
38.7907339 -121.2357828
38.3396367 -122.70109840000002
33.756961499999996 -118.3539613
33.787794299999995 -118.3581284
34.0805651 -118.072846
38.752123499999996 -121.28800590000002
37.9624239 -122.55497749999999
38.5815719 -121.49439960000001
38.5052429 -122.4703868
36.6777372 -121.6555013
37.9746458 -122.56164479999998
34.1083449 -117.2897652
37.6304904 -122.41108349999999
37.5071591 -122.26052220000001
33.4273521 -117.61260039999999
32.715738 -117.1610838
34.1066756 -117.8067257
34.2819461 -118.4389719
37.7749295 -122.4194155
34.09611110000001 -118.10583329999999
33.783908399999994 -116.95863500000002
36.6066162 -120.1890447
37.338208200000004 -121.88632859999998
36.84551079999999 -121.53799740000002
33.5019027 -117.6627655
37.7249296 -122.1560768
35.2827524 -120.6596156
33.1433723 -117.1661449
34.121396999999995 -118.1064585
37.562991700000005 -122.32552539999999
37.96214570000001 -122.3455263
37.9735346 -122.5310874
37.7799273 -121.9780153
36.6171819 -121.8482855
36.708006 -119.5559652
33.7454725 -117.867653
34.4208305 -119.69819009999999
37.354107899999995 -121.9552356
34.3916641 -118.54258600000001
36.9741171 -122.0307963
33.9472359 -118.08534509999998
34.953033700000006 -120.43571909999999
34.01945429999999 -118.4911912
34.3541659 -119.05927050000001
38.440428999999995 -122.7140548
32.8383828 -116.97391670000002
37.2638324 -122.0230146
37.8590937 -122.4852507
37.051059499999994 -122.0146841
33.7414085 -118.10476820000001
36.614921700000004 -121.822098
38.4021359 -122.82388059999998
36.5707838 -119.61207649999999
35.500513899999994 -119.2717761
40.6804279 -122.3708419
34.1616729 -118.0528456
33.8044614 -118.1678456
34.2694474 -118.78148200000001
32.991155 -117.27114809999999
36.424687 -121.32631869999999
34.5958201 -120.13764809999999
38.291859 -122.45803559999999
37.982949600000005 -120.38217240000002
34.0519548 -118.04673390000002
33.954737 -118.21201609999999
38.939926 -119.9771868
34.1161196 -118.15034879999999
37.654656 -122.40774979999999
33.8028875 -117.9931203
37.9577016 -121.29077959999998
38.2382474 -122.040244
37.368829999999996 -122.03634960000001
40.4162842 -120.6530063
38.3929675 -120.8024357
35.142467100000005 -119.4565078
35.1321877 -118.44897390000001
40.0271015 -122.12332279999998
33.4936391 -117.14836480000001
34.1072305 -118.05784560000001
34.1705609 -118.83759369999999
37.87353770000001 -122.4566392
33.835849200000006 -118.34062879999999
37.7396513 -121.42522269999999
41.05929099999999 -124.14312460000001
39.327962 -120.1832533
36.20772879999999 -119.3473379
41.955988399999995 -121.4774916
37.494656799999994 -120.84659409999999
33.7420005 -117.82363909999998
34.135558200000006 -116.05416890000001
39.1501709 -123.2077831
37.59339179999999 -122.0438298
34.09751 -117.64838759999999
38.3565773 -121.98774440000001
38.1040864 -122.25663670000002
34.28049229999999 -119.2945199
34.003903 -118.230073
34.5362184 -117.29276409999999
33.81400620000001 -117.8220723
36.330228399999996 -119.2920585
33.2000368 -117.2425355
34.020289399999996 -117.86533859999999
37.9100783 -122.06518190000001
35.5941238 -119.34094569999999
37.6413202 -120.7604834
36.910231 -121.7568946
41.42264979999999 -122.38612690000001
34.0686208 -117.93895259999998
34.0900091 -118.3617443
38.5804609 -121.53023400000001
34.1466467 -118.8073729
33.75917570000001 -117.9897058
33.0372674 -115.6213817
39.0098946 -121.4230133
33.97917929999999 -118.032844
33.5989126 -117.2800372
39.154613700000006 -122.1494187
39.4096079 -123.35556559999999
39.5243265 -122.19359309999999
38.547132700000006 -122.81638020000001
38.5249065 -121.9708017
36.413560499999996 -119.0987176
38.67851570000001 -121.7732971
37.429938799999995 -122.2538557
33.88850350000001 -117.8132571
38.40157809999999 -122.3608105
41.735418599999996 -122.6344709
39.1404477 -121.6169108
34.033625 -117.0430865
34.114174299999995 -116.432235

In [13]:
# Make the list into series
uv = pd.Series(uv_index)

In [14]:
# Add the values to city_df
city_df['UV_value'] = uv.values

In [15]:
city_df.head()

,city,type,county,state,lat,lng,UV_value
0,Adelanto,City,San Bernardino,california,34.582770,-117.409215,2.98
1,Agoura Hills,City,Los Angeles,california,34.153340,-118.761676,3.00
2,Alameda,City,Alameda,california,37.765206,-122.241636,2.00
3,Albany,City,Alameda,california,37.886870,-122.297748,1.97
4,Alhambra,City,Los Angeles,california,34.095287,-118.127015,3.00

In [16]:
# Convert Dataframe to JSON
city_df.to_csv("uv_data.csv")

In [2]:
def uv_index():
    uv_index = []
    for i, r in city_df.iterrows():
        uvi = owm.uvindex_around_coords(r.loc['lat'], r.loc['lng'])
        uv_index.append(uvi.get_value())
    return uv_index